sudo: required
dist: trusty
language: cpp
os:
  - linux
  - osx

compiler:
  - clang
  - gcc

branches:
  only:
    - master

env:
  - CONFIG=Debug

before_install:
  # update to gcc7 with c++11/14 support
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        && sudo apt-get update -qq;
    fi

install:
  # install latest CMake 3.10.0
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
        wget --no-check-certificate https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz
        && tar -xzf cmake-3.10.0-Linux-x86_64.tar.gz
        && sudo cp -fR cmake-3.10.0-Linux-x86_64/* /usr;
    fi
  # install project dependencies
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
        sudo apt-get install -qq gcc-7 g++-7 libboost1.55-all-dev git
        && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
        && sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90;
    fi
  # install latest lcov
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
        wget --no-check-certificate http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz
        && tar -xf lcov_1.13.orig.tar.gz
        && sudo make -C lcov-1.13/ install;
    fi
  - gem install coveralls-lcov

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$CONFIG ..

script:
  - travis_wait 60 cmake --build . --target all
  - ctest .
