version: 2
jobs:
  configure:
    docker:
      - image: newproggie/paramount:1.0.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Configure ParamountSuperbuild
          command: |
            git submodule sync
            git submodule update --init
            mkdir build && cd build
            cmake -DUSE_SYSTEM_QT=ON -DCMAKE_PREFIX_PATH=${QT5_DIR} ..
      - persist_to_workspace:
          root: .
          paths: build/*
  build:
    docker:
      - image: newproggie/paramount:1.0.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Build ParamountSuperbuild
          command: |
            git submodule sync
            git submodule update --init
            cmake --build build/
      - persist_to_workspace:
          root: .
          paths: build/*
  test:
    docker:
      - image: newproggie/paramount:1.0.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Test ParamountSuperbuild
          command: |
            cd build/
            ctest .
workflows:
  version: 2
  configure-build-and-test:
    jobs:
      - configure
      - build:
          requires:
            - configure
      - test:
          requires:
            - build
